const data = [
  { id: 1, category: 1, region: 'North America', count: 367, month: 'январь' },
  { id: 2, category: 1, region: 'Western Europe', count: 66, month: 'февраль' },
  { id: 3, category: 1, region: 'Asia', count: 53, month: 'март' },
  { id: 4, category: 2, region: 'Latin America & Caribbean', count: 19, month: 'апрель' },
  { id: 5, category: 2, region: 'Australia & New Zealand', count: 16, month: 'май' },
  { id: 6, category: 2, region: 'Russian Commonwealth', count: 13, month: 'июнь' },
  { id: 7, category: 3, region: 'Eastern Europe', count: 13, month: 'июль' },
  { id: 8, category: 3, region: 'Middle East', count: 9, month: 'август' },
  { id: 9, category: 3, region: 'North America', count: 367, month: 'сентябрь' },
  { id: 10, category: 3, region: 'Western Europe', count: 66, month: 'октябрь' },
  { id: 11, category: 3, region: 'Asia', count: 53, month: 'ноябрь' },
  { id: 12, category: 3, region: 'Latin America & Caribbean', count: 19, month: 'декабрь' },
  { id: 13, category: 3, region: 'Australia & New Zealand', count: 16, month: 'январь' },
  { id: 14, category: 3, region: 'Russian Commonwealth', count: 13, month: 'февраль' },
  { id: 15, category: 3, region: 'Eastern Europe', count: 13, month: 'март' },
  { id: 16, category: 3, region: 'Middle East', count: 9, month: 'апрель' },
  { id: 17, category: 3, region: 'South Africa', count: 7, month: 'май' },
  { id: 18, category: 3, region: 'North Africa', count: 6, month: 'июнь' },
  { id: 19, category: 3, region: 'Baltics', count: 2, month: 'июль' },
  { id: 20, category: 4, region: 'South Africa', count: 7, month: 'август' },
  { id: 21, category: 4, region: 'North Africa', count: 6, month: 'сентябрь' },
  { id: 22, category: 5, region: 'Baltics', count: 2, month: 'октябрь' },
  { id: 23, category: 5, region: 'Central Asia', count: 10, month: 'ноябрь' },
  { id: 24, category: 6, region: 'Scandinavia', count: 18, month: 'декабрь' },
  { id: 25, category: 6, region: 'Southeast Asia', count: 30, month: 'январь' }
];